#!/bin/bash

# Test partition alignment on a given disk

if [[ $(/usr/bin/id -u) -ne 0 ]]
then
  echo 'Please run this script as the "root" user (uid 0).'
  exit 1
fi

DISK=$1

if [ -z "$DISK" ]
then
  echo 'ERROR: Specify disk to examine as parameter 1.'
  exit 2
fi

if [ ! -b $DISK ]
then
  echo 'ERROR: Device does not exist or is not a block device: '"$DISK"
  exit 3
fi

echo 'Checking partition alignment on disk '"$DISK"'...'
PARTITIONS=$(sudo parted $DISK print --machine | tail -n+3 | cut -d ':' -f1 | sort -n)
for PARTITION in $PARTITIONS
do
  echo -n $DISK
  sudo parted $DISK align-check opt $PARTITION
done
