#!/bin/bash

# Simplistic, non error handling script to determine Ubuntu cd mirrors supporting HTTPS

curl https://launchpad.net/ubuntu/+cdmirrors > /tmp/cdmirrors.html
sed -e '1,/<table class="listing" id="mirrors_list">/d' /tmp/cdmirrors.html | sed -e '/<\/table>/,$d' | grep -F '<a href="http://' | cut -d '"' -f2 | sed 's/^http:/https:/g' > /tmp/cdmirrors_https.lst
while read URL; do curl --silent --head --connect-timeout 3 --max-time 8 $URL/ls-lR.gz >/dev/null && echo $URL; done </tmp/cdmirrors_https.lst
